data:
  - attributes:
      created_at: '2021-03-10T16:08:43.242616'
      destination_override_endpoint: 'http://fake:8000'
      entries:
        - classifiers: {}
          config:
            condition: AND
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /payload
          id: 9d0805ac-1880-4e06-b18f-950a88465663
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.credit
          transformer_config_map: null
          type: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: e5f01942-fc5c-4660-871f-10800de179b4
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: lawn-green-dresser
        source: vgs-satellite
    id: e5f01942-fc5c-4660-871f-10800de179b4
    type: rule_chain
version: 1
