job-defaults: &job-defaults
  working_directory:
    ~/fake-service

version: 2
jobs:
  test:
    machine:
      image: circleci/classic:201808-01
    <<: *job-defaults
    steps:
      - checkout
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          name: "Build Docker"
          command: |
            docker build -t fake-service .
            docker-compose build
            docker-compose up -d fake-service
            docker-compose up -d satellite
            ./test.sh

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
